---
development:
  cloud_name: hflsgfpew
  api_key: '865141574666118'
  api_secret: xzaGLpIEh-vFTBOGEfJJ8C18ViQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hflsgfpew
  api_key: '865141574666118'
  api_secret: xzaGLpIEh-vFTBOGEfJJ8C18ViQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hflsgfpew
  api_key: '865141574666118'
  api_secret: xzaGLpIEh-vFTBOGEfJJ8C18ViQ
  enhance_image_tag: true
  static_image_support: false
